apiVersion: 2019-12-01
location: germanywestcentral
name: webshop-group
properties:
  imageRegistryCredentials:
  - server: cloudcocos.azurecr.io
    username: CloudCocos
  containers:
  - name: db
    properties:
      image: cloudcocos.azurecr.io/postgres:latest
      resources:
        requests:
          cpu: 0.5
          memoryInGb: 1.5
      environmentVariables:
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_PASSWORD
        value: "postgres"
      - name: POSTGRES_DB
        value: "shop"
      ports:
      - port: 5432
  - name: redis
    properties:
      image: cloudcocos.azurecr.io/redis:latest
      resources:
        requests:
          cpu: 0.5
          memoryInGb: 0.5
      ports:
      - port: 6379
  - name: webshop-backend
    properties:
      image: cloudcocos.azurecr.io/webshop-backend:latest
      resources:
        requests:
          cpu: 0.5
          memoryInGb: 1
      ports:
      - port: 8000
      environmentVariables:
      - name: DB_URL_PROD
        value: "postgres://postgres:postgres@db:5432/shop"
      - name: CELERY_BROKER_URL
        value: "redis://redis:6379/0"
      - name: CELERY_RESULT_BACKEND
        value: "redis://redis:6379/0"
  - name: celery-worker
    properties:
      image: cloudcocos.azurecr.io/celery-worker:latest
      resources:
        requests:
          cpu: 0.5
          memoryInGb: 1
      command:
      - "celery"
      - "-A"
      - "tasks.celery_app"
      - "worker"
      - "--loglevel=info"
      environmentVariables:
      - name: DB_URL_PROD
        value: "postgres://postgres:postgres@db:5432/shop"
      - name: CELERY_BROKER_URL
        value: "redis://redis:6379/0"
      - name: CELERY_RESULT_BACKEND
        value: "redis://redis:6379/0"
  - name: webshop-frontend
    properties:
      image: cloudcocos.azurecr.io/webshop-frontend:latest
      resources:
        requests:
          cpu: 0.5
          memoryInGb: 0.5
      ports:
      - port: 80
  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 80
    - protocol: tcp
      port: 8000
  restartPolicy: OnFailure
