version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    #ports:
      #- "5432:5432"
    # ports need to be removed in production

  redis:
    image: redis:latest
    #ports:
    #  - "6379:6379"
    

  webshop-backend:
    image: cloudcocos.azurecr.io/webshop-backend:latest  
    ports:
      - "8000:8000"
    environment:
      DB_URL_PROD: "postgres://postgres:postgres@db:5432/shop"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    depends_on:
      - db
      - redis

  celery-worker:
    image: cloudcocos.azurecr.io/celery-worker:latest
    command: ["celery", "-A", "tasks.celery_app", "worker", "--loglevel=info"]
    environment:
      DB_URL_PROD: "postgres://postgres:postgres@db:5432/shop"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    depends_on:
      - db
      - redis
      - webshop-backend

  webshop-frontend:
    image: cloudcocos.azurecr.io/webshop-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - webshop-backend
#