[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "azure-storage-blob>=12.19.0",
    "python-multipart>=0.0.7",  # Required for handling file uploads
]
